### PR TITLE
macOS: titlebar in borderless fullscreen fix

### LINKED ISSUE #1195: Fullscreen Titlebar Won't Show on macOS
While in an exclusive fullscreen mode on macOS, the titlebar (while hovering over the top of the screen) doesn't slide down as expected. I've confirmed this issue with `cargo run --example window` from this repo. This issue seems to have been introduced in 5bc3cf18d98aef0a5f0a51c0cf655d37af833730 with the merge of #925.

This was originally brought to our attention in https://github.com/jwilm/alacritty/pull/2438#issuecomment-536649468.

### PR DESCRIPTION
**Pull request by tinaun**
Fixes #1195, but does not implement the user-facing changes talked about in that issue (should we create a new issue for that feature?)

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by tinaun** [comment]
I didn't realize there was a 2-year old pr doing much the same thing (#1326) also sitting in waiting-for-review purgatory when I wrote this pr. 

I didn't include any logic for handling the borderless fullscreen <-> exclusive fullscreen in this pr, because you can get around it in user code easier than you can work around "pressing the fullscreen button on a window prevents you from leaving unless you close the program"

**Comment by francesca64** [comment]
@tinaun which PR do you think would be more ideal to merge, assuming both are equally likely to be accepted?

**Comment by tinaun** [comment]
that pr has a bug with its handling of the exclusive -> borderless logic that would need to be included in the pull request if you wanted to merge that one (it might be fixed in the branch mentioned here, i haven't tested it https://github.com/rust-windowing/winit/pull/1326#issuecomment-933350528)

**Comment by francesca64** [comment]
@tinaun gotcha, thanks for the insight.

@irh would you still be interested in helping push this forward?

**Comment by bschwind** [comment]
Hi, how can I help test this? Is it enough to run the window example with `cargo run --example window`, go into borderless fullscreen with the green maximize button, and verify the menu bar is still available when moused over?

**Comment by irh** [comment]
@francesca64 Yes I'd be happy to help out here, although it's not clear to me what needs to be done? I think #1326 feels complete with my extra commit in place, but I'm no expert in windowing (I just found the PR and figured I'd see if I could help) so I could be missing something. I'd also be happy to see this PR get landed to solve the main problem of fullscreen on macOS and then leave the mode switching behaviour to be refined in a followup.

**Comment by francesca64** [comment]
@irh you wrote a detailed commit description, so that makes you automatically reputable! This is a small enough change that I don't think there's any need for us to split it up into multiple passes. Your branch is the most complete, so if you open a PR for it, we can move forward with merging it!

@bschwind thanks for the interest! Doing that will test the most common case, though the edge case of switching between exclusive and borderless fullscreen is the thornier aspect to this.

**Comment by irh** [comment]
OK thanks @francesca64 =) I've opened #2053.

**Comment by francesca64** [comment]
Subsumed by #2053
