### ISSUE TITLE
winit 0.30.12 fails to compile on Rust 1.92+: E0282 type annotations needed in Window closures

### ISSUE THREAD

**Issue by johnproblems** [rust-windowing/winit#4486]
## Description

winit 0.30.12 fails to compile on **Rust 1.92 and newer** (including stable 1.93.1) with 59 `E0282` "type annotations needed" errors in `src/window.rs`.

The closure parameters in `maybe_wait_on_main` and `maybe_queue_on_main` calls can no longer be inferred by the compiler:

```
error[E0282]: type annotations needed
    --> winit-0.30.12/src/window.rs:1578:41
     |
1578 |         self.window.maybe_wait_on_main(|w| w.set_cursor_hittest(hittest))
     |                                         ^  - type must be known at this point
```

## Steps to Reproduce

1. Use any Rust version >= 1.92 (e.g., `stable 1.93.1` or `nightly-2026-02-14`)
2. Add `winit = "0.30.12"` with X11 or Wayland features enabled
3. `cargo build` → 59 `E0282` errors

## Affected Versions

Tested and confirmed failing on:

| Toolchain | rustc version | Errors |
|---|---|---|
| stable 1.93.1 | 1.93.1 | 63 |
| nightly-2025-10-01 | 1.92.0 | 63 |
| nightly-2025-12-01 | 1.93.0 | 63 |
| nightly-2026-01-15 | 1.94.0 | 63 |
| nightly-2026-02-05 | 1.95.0 | 59 |
| nightly-2026-02-10 | 1.95.0 | 59 |
| nightly-2026-02-14 | 1.95.0 | 59 |

## Root Cause

The closures passed to `maybe_wait_on_main(|w| ...)` and `maybe_queue_on_main(|w| ...)` in `src/window.rs` rely on type inference to determine that `w` is `&platform_impl::Window`. Starting with Rust 1.92, the compiler can no longer infer this.

Additionally, 3 inner closures calling `.map(|f| f.into())` on `Fullscreen` types have the same inference failure.

## Fix

Adding explicit type annotations resolves all errors:
- `|w|` → `|w: &platform_impl::Window|`
- `|f| f.into()` → `|f: platform_impl::Fullscreen| f.into()` (or `Fullscreen` for the outer type)

I have a PR ready with this fix.

**Comment by madsmtm** [comment]
I cannot reproduce with:
```
$ cargo --version
cargo 1.93.1 (083ac5135 2025-12-15)
$ cargo build --target x86_64-unknown-linux-gnu
```

Are you sure it's not actually a problem in `rust-analyzer` that you're seeing?

**Comment by johnproblems** [comment]
Thanks for checking! I can confirm this compiles successfully on **nightly-2026-02-14** with our patch applied. 

The issue might have been specific to certain nightly builds or rust-analyzer false positives. However, the explicit type annotations are still valuable because:

1. They improve rust-analyzer's ability to provide accurate diagnostics
2. They make the code more explicit and easier to understand
3. They follow Rust best practices for complex closure signatures

Whether or not this gets merged, we'll keep the vendored patch in our project since it improves our IDE experience and code clarity.

**Comment by madsmtm** [comment]
I'm not gonna merge it, report the problem upstream to Rust-Analyzer if that is indeed the problem

**Comment by johnproblems** [comment]
After further investigation, I need to provide an update.

## What Happened

During initial development on nightly-2026-02-10, we encountered 59 E0282 type inference errors when compiling winit 0.30.12. The errors were real and blocking our build. We implemented explicit type annotations for the closure parameters, which resolved the issue.

## Current Status  

When attempting to reproduce the errors on clean builds across multiple nightly versions (2025-10-01 through 2026-02-14), cargo compiles successfully without any type annotations. This suggests the issue was environment-specific or related to incremental compilation state.

## Conclusion

While I encountered real compilation errors initially, I cannot reliably reproduce them on clean builds. This may have been:
- An incremental compilation bug (since resolved)
- Environment-specific configuration
- An issue that was fixed in Rust between nightlies

I'm closing the associated PR #4487. The explicit type annotations do improve code clarity, but without reproducible errors, they don't meet the bar for upstream contribution.

Apologies for the noise, and thank you for the feedback.

**Comment by romch007** [comment]
I can reproduce the issue on `1.95.0-nightly` and `1.93.1`. It's definitely a compilation error and not related to rust-analyzer.

**Comment by madsmtm** [comment]
How can you reproduce?

**Comment by romch007** [comment]
My bad, it looks like I was using winit without the proper features enabled:

<img width="2217" height="714" alt="Image" src="https://github.com/user-attachments/assets/33a7d1e4-c312-4073-9132-dc89e766e1ba" />
